### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [LLNL/scraper#52]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.8.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary llnl-scraper -w /tmp/ext llnl-scraper==0.8.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting llnl-scraper==0.8.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/e26/782a0d6ef4e01/llnl-scraper-0.8.1.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-t008rs89/llnl-scraper/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-t008rs89/llnl-scraper/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-t008rs89/llnl-scraper/pip-egg-info
         cwd: /tmp/pip-wheel-t008rs89/llnl-scraper/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-t008rs89/llnl-scraper/setup.py", line 9, in <module>
        with open('requirements/production.txt') as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements/production.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by IanLee1521** [comment]
@thatch - Thanks for reporting... would you be willing to submit a PR adding the fix to the project?
